# -*- coding: utf-8 -*-
"""OOP_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dp3Ee3E523_AvA7CtkTiB7phEJeA4Jto
"""

class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

car1, car2, car3 = Car("Honda", "civic", 2020), Car("Honda", "CRV", 2024), Car("Honda", "HRV", 2022)

cars = [car1, car2, car3]

for car in cars:
    print(f'{car.make} {car.model} {car.year}')

"""Jalyn Buthman mini oop project 3"""